apiVersion: v1
kind: Namespace
metadata:
  name: asodemo
---
apiVersion: microsoft.resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: asodemo-rg
  namespace: asodemo
spec:
  location: westus2
---
apiVersion: microsoft.dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServer
metadata:
  name: ${SERVER}
  namespace: asodemo
spec:
  location: westus2
  owner:
    name: asodemo-rg
  version: "13"
  sku:
    name: Standard_D4s_v3
    tier: GeneralPurpose
  administratorLogin: ${USERNAME}
  administratorLoginPassword: ${PASSWORD}
  storage:
    storageSizeGB: 128
---
apiVersion: microsoft.dbforpostgresql.azure.com/v1alpha1api20210601
kind: FlexibleServersDatabase
metadata:
  name: votedb
  namespace: asodemo
spec:
  owner:
    name: ${SERVER}
  charset: utf8
---
apiVersion: microsoft.serviceconnector.azure.com/v1alpha1api20210601
kind: serviceconnector
metadata:
  name: sc
  namespace: asodemo
spec:
  target:
    name: votedb
    type: FlexibleServersDatabase
  auth:
    type: secret
    username: ${USERNAME}
    password: ${PASSWORD}